export const FinancialStatements = Object.freeze({
  Profit: Symbol('Profit'),
  Revenue: Symbol('Revenue'),
});

export const Sectors = Object.freeze({
  CommercialServices: Symbol('Commercial Services'),
  Communications: Symbol('Communications'),
  ConsumerDurables: Symbol('Consumer Durables'),
  ConsumerNonDurables: Symbol('Consumer Non-Durables'),
  ConsumerServices: Symbol('Consumer Services'),
  DistributionServices: Symbol('Distribution Services'),
  ElectronicTechnology: Symbol('Electronic Technology'),
  EnergyMinerals: Symbol('Energy Minerals'),
  Finance: Symbol('Finance'),
  HealthServices: Symbol('Health Services'),
  HealthTechnology: Symbol('Health Technology'),
  IndustrialServices: Symbol('Industrial Services'),
  Miscellaneous: Symbol('Miscellaneous'),
  NonEnergyMinerals: Symbol('Non-Energy Minerals'),
  ProcessIndustries: Symbol('Process Industries'),
  ProducerManufacturing: Symbol('Producer Manufacturing'),
  RetailTrade: Symbol('Retail Trade'),
  TechnologyServices: Symbol('Technology Services'),
  Transportation: Symbol('Transportation'),
  Utilities: Symbol('Utilities'),
});

export const Industries = Object.freeze({
  AerospaceDefense: Symbol('Aerospace & Defense'),
  AgriculturalCommoditiesMilling: Symbol('Agricultural Commodities/Milling'),
  Airlines: Symbol('Airlines'),
  Aluminum: Symbol('Aluminum'),
  ApparelFootwearRetail: Symbol('Apparel/Footwear Retail'),
  AutoPartsOem: Symbol('Auto Parts: OEM'),
  BeveragesAlcoholic: Symbol('Beverages: Alcoholic'),
  Biotechnology: Symbol('Biotechnology'),
  Broadcasting: Symbol('Broadcasting'),
  BuildingProducts: Symbol('Building Products'),
  ChemicalsAgricultural: Symbol('Chemicals: Agricultural'),
  ChemicalsSpecialty: Symbol('Chemicals: Specialty'),
  Coal: Symbol('Coal'),
  ConstructionMaterials: Symbol('Construction Materials'),
  DataProcessingServices: Symbol('Data Processing Services'),
  DrugstoreChains: Symbol('Drugstore Chains'),
  ElectricUtilities: Symbol('Electric Utilities'),
  ElectronicComponents: Symbol('Electronic Components'),
  ElectronicsApplianceStores: Symbol('Electronics/Appliance Stores'),
  EngineeringConstruction: Symbol('Engineering & Construction'),
  FinanceRentalLeasing: Symbol('Finance/Rental/Leasing'),
  FinancialConglomerates: Symbol('Financial Conglomerates'),
  FoodMeatFishDairy: Symbol('Food: Meat/Fish/Dairy'),
  FoodRetail: Symbol('Food Retail'),
  FoodSpecialtyCandy: Symbol('Food: Specialty/Candy'),
  GasDistributors: Symbol('Gas Distributors'),
  HomeFurnishings: Symbol('Home Furnishings'),
  Homebuilding: Symbol('Homebuilding'),
  HospitalNursingManagement: Symbol('Hospital/Nursing Management'),
  HouseholdPersonalCare: Symbol('Household/Personal Care'),
  IndustrialConglomerates: Symbol('Industrial Conglomerates'),
  IndustrialMachinery: Symbol('Industrial Machinery'),
  InsuranceBrokersServices: Symbol('Insurance Brokers/Services'),
  IntegratedOil: Symbol('Integrated Oil'),
  InternetRetail: Symbol('Internet Retail'),
  InternetSoftwareServices: Symbol('Internet Software/Services'),
  InvestmentBanksBrokers: Symbol('Investment Banks/Brokers'),
  InvestmentManagers: Symbol('Investment Managers'),
  InvestmentTrustsMutualFunds: Symbol('Investment Trusts/Mutual Funds'),
  MarineShipping: Symbol('Marine Shipping'),
  MetalFabrication: Symbol('Metal Fabrication'),
  MiscellaneousCommercialServices: Symbol('Miscellaneous Commercial Services'),
  MiscellaneousManufacturing: Symbol('Miscellaneous Manufacturing'),
  MotorVehicles: Symbol('Motor Vehicles'),
  OilGasProduction: Symbol('Oil & Gas Production'),
  OilRefiningMarketing: Symbol('Oil Refining/Marketing'),
  OilfieldServicesEquipment: Symbol('Oilfield Services/Equipment'),
  OtherMetalsMinerals: Symbol('Other Metals/Minerals'),
  OtherTransportation: Symbol('Other Transportation'),
  PharmaceuticalsOther: Symbol('Pharmaceuticals: Other'),
  PreciousMetals: Symbol('Precious Metals'),
  Railroads: Symbol('Railroads'),
  RealEstateDevelopment: Symbol('Real Estate Development'),
  RegionalBanks: Symbol('Regional Banks'),
  Restaurants: Symbol('Restaurants'),
  SpecialtyTelecommunications: Symbol('Specialty Telecommunications'),
  Steel: Symbol('Steel'),
  Trucking: Symbol('Trucking'),
  TrucksConstructionFarmMachinery: Symbol('Trucks/Construction/Farm Machinery'),
  WholesaleDistributors: Symbol('Wholesale Distributors'),
  WirelessTelecommunications: Symbol('Wireless Telecommunications'),
});
